/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f401xx.h"

void delay()
{
	for(int i=0; i<100000; i++)
	{}
}

int main(void)
{
	GPIO_Handle_t gpioLedHandle;
	GPIO_Handle_t gpioButtonHandle;

	// Setting up LED handle
	gpioLedHandle.pGPIOx = GPIOA;
	gpioLedHandle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	gpioLedHandle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NUMBER_5;
	gpioLedHandle.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
	gpioLedHandle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	gpioLedHandle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

	// Setting up the button handle
	gpioButtonHandle.pGPIOx = GPIOC;
	gpioButtonHandle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	gpioButtonHandle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NUMBER_13;
	gpioButtonHandle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	gpioButtonHandle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// Enabling the clock for both of them
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_PeriClockControl(GPIOC, ENABLE);

	// Initialise the GPIO registers for A and C
	GPIO_Init(&gpioLedHandle);
	GPIO_Init(&gpioButtonHandle);

    /* Loop forever */
	for(;;)
	{
		// Toggle the pin
		uint8_t value = GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NUMBER_13);
		if(value == 0) {
			delay();
			GPIO_ToggleOutputPin(gpioLedHandle.pGPIOx, gpioLedHandle.GPIO_PinConfig.GPIO_PinNumber);
		}
	}
}
